// <auto-generated> Added UserWorkItemStatus entity to match T-SQL schema </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models;

[Table("UserWorkItemStatuses")]
public partial class UserWorkItemStatus
{
    [Key]
    [Column("UserId", Order = 0)]
    public int UserId { get; set; }

    [Key]
    [Column("WorkItemId", Order = 1)]
    public int WorkItemId { get; set; }

    public bool IsConfirmed { get; set; }

    public DateTime UpdatedAt { get; set; }

    // Navigation
    public virtual User User { get; set; }
    public virtual WorkItem WorkItem { get; set; }
}
