// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Table("Users")]
public partial class User
{
    /// <summary>
    /// 識別編碼
    /// </summary>
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// 使用者帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    /// <summary>
    /// 密碼雜湊
    /// </summary>
    [Required]
    public string PasswordHash { get; set; }

    /// <summary>
    /// 角色 ('Admin' 或 'User')
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Role { get; set; }

    // Navigation properties
    public virtual ICollection<UserWorkItemStatus> UserWorkItemStatuses { get; set; }
}