// <auto-generated> Added WorkItem entity to match T-SQL schema </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DataAccess.Models;

[Table("WorkItems")]
public partial class WorkItem
{
    [Key]
    [Column("Id")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<UserWorkItemStatus> UserWorkItemStatuses { get; set; }
}
